import { Product } from './types';

export const DEMO_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Classic Black T-Shirt',
    price: 450,
    category: 'Classic',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'Dark Gray'],
    description: 'A timeless classic essential. 100% premium cotton for ultimate comfort.',
    stock: 50,
    imageUrl: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '2',
    name: 'White Oversized T-Shirt',
    price: 550,
    category: 'Oversized',
    sizes: ['M', 'L', 'XL'],
    colors: ['White', 'Off-White'],
    description: 'Modern relaxed fit with dropped shoulders. Perfect for streetwear style.',
    stock: 30,
    imageUrl: 'https://images.unsplash.com/photo-1562157873-818bc0726f68?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '3',
    name: 'Graphic Streetwear Tee',
    price: 650,
    category: 'Graphic',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black', 'Navy'],
    description: 'Bold custom graphic print on heavyweight cotton. Unique urban aesthetic.',
    stock: 20,
    imageUrl: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '4',
    name: 'Couple T-Shirt Set',
    price: 700,
    category: 'Couple',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Pink', 'Blue', 'White'],
    description: 'Matching set for couples. High quality soft fabric with adorable minimal prints.',
    stock: 15,
    imageUrl: 'https://images.unsplash.com/photo-1527719327859-c6ce80353573?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '5',
    name: 'Premium Cotton T-Shirt',
    price: 500,
    category: 'Premium',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Royal Blue', 'Forest Green', 'Burgundy'],
    description: 'Luxury grade Pima cotton. Silky smooth texture and superior durability.',
    stock: 25,
    imageUrl: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '6',
    name: 'Custom Print T-Shirt',
    price: 800,
    category: 'Custom',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Custom Color'],
    description: 'Upload your own design! We use high-quality DTG printing for your unique tee.',
    stock: 100,
    imageUrl: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&q=80&w=800',
  },
];
